// backend/routes/leads.js
const express = require("express");
const rateLimit = require("express-rate-limit");
const { createClient } = require("@supabase/supabase-js");

const router = express.Router();

const supabase = createClient(
  process.env.SUPABASE_URL,
  process.env.SUPABASE_SERVICE_KEY
);

// ===============================
// Spam protection (no IP stored)
// ===============================
// Uses IP in-memory only for throttling. Nothing is written to DB.
const leadLimiter = rateLimit({
  windowMs: 60 * 60 * 1000, // 1 hour
  max: 10,                  // adjust: 10 per hour per IP
  standardHeaders: true,
  legacyHeaders: false
});

// Extra: simple validators
function normalizeEmail(email) {
  return (email || "").trim().toLowerCase();
}

function isValidEmail(email) {
  // matches your DB constraint style
  return /^[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,}$/i.test(email);
}

function isValidE164(phone) {
  // + plus 8..15 digits total (E.164-ish)
  return /^\+[1-9]\d{7,14}$/.test(phone);
}

// ===============================
// POST /api/leads
// ===============================
router.post("/", leadLimiter, async (req, res) => {
  try {
    const {
      email,
      phone,          // expect either null or E.164 string like +14155552671
      phone_country,  // optional
      phone_dial,     // optional
      consent_updates,
      website,        // honeypot (should be empty)
      ts              // optional client timestamp (ms)
    } = req.body || {};

    // Honeypot: real users won't fill this
    if (typeof website === "string" && website.trim() !== "") {
      return res.status(200).json({ ok: true }); // pretend success
    }

    const emailNorm = normalizeEmail(email);

    if (!emailNorm || !isValidEmail(emailNorm)) {
      return res.status(400).json({ error: "Invalid email" });
    }

    if (!consent_updates) {
      return res.status(400).json({ error: "Consent required" });
    }

    // Optional timing check (blocks instant-submit bots)
    // If you send ts from the page load time, reject < 1200ms
    if (typeof ts === "number") {
      const delta = Date.now() - ts;
      if (delta < 1200) {
        return res.status(429).json({ error: "Too fast. Please try again." });
      }
      // also reject crazy old timestamps
      if (delta > 1000 * 60 * 60 * 24 * 7) {
        return res.status(400).json({ error: "Invalid request." });
      }
    }

    let phoneE164 = null;
    if (phone) {
      const p = String(phone).trim();
      if (!isValidE164(p)) {
        return res.status(400).json({ error: "Invalid phone number" });
      }
      phoneE164 = p;
    }

    // Insert (email_normalized is generated by DB)
    const { error } = await supabase.from("leads").insert({
      email: emailNorm,
      phone_e164: phoneE164,
      phone_country: phone_country || null,
      phone_dial: phone_dial || null,
      consent_updates: true
    });

    if (error) {
      // Unique violation -> treat as success (prevents retry spam)
      // Postgres unique violation is usually 23505
      if (error.code === "23505") {
        return res.status(200).json({ ok: true, duplicate: true });
      }
      console.error("Supabase insert error:", error);
      return res.status(500).json({ error: "Server error" });
    }

    return res.json({ ok: true });
  } catch (err) {
    console.error("Lead endpoint failed:", err);
    return res.status(500).json({ error: "Server error" });
  }
});

module.exports = router;
